# Docker Compose para el servidor MCP de Holded
version: '3.8'

services:
  holded-mcp:
    build: .
    container_name: holded-mcp-server
    restart: unless-stopped
    
    # Variables de entorno
    environment:
      - HOLDED_API_KEY=${HOLDED_API_KEY:-YOUR_HOLDED_API_KEY}
      - PORT=3000
      - NODE_ENV=production
    
    # Puerto para el servidor MCP
    ports:
      - "3000:3000"
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Límites de recursos
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    volumes:
      - holded-logs:/app/logs
    
    # Red personalizada (opcional)
    networks:
      - holded-network
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Volúmenes
volumes:
  holded-logs:
    driver: local

# Redes
networks:
  holded-network:
    driver: bridge
    
  # Si necesitas conectar con otros servicios existentes
  # external-network:
  #   external: true
